default: &default
    adapter: postgresql
    encoding: unicode
    username: <%= ENV["POSTGRES_USER"]%>
    host: localhost
    timeout: 5000
    pool: <%= ENV.fetch("DB_MAX_THREADS") { 10 } %>
    host: <%= ENV["POSTGRES_HOST"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: planto_dev

test:
  <<: *default
  database: planto_test

production:
  <<: *default
  database: planto_prod
