default: &default
    adapter: postgresql
    encoding: unicode
    username: postgres
    host: localhost
    timeout: 5000

development:
  <<: *default
  database: planto_dev

test:
  <<: *default
  database: planto_test

production:
  <<: *default
  database: planto_prod
